# Site settings
title: Just for fun
author: cothee
author_avatar: /images/header.jpg
email: cothee@gmail.com
description: something for life
url: "https://cothee.github.io"
#domain: "http://dongyado.com"
github_username: cothee
github_site_repo: cothee/cothee.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


plugins:
  - jekyll-sitemap
